defaultSettings:
  storageMinimalAvailablePercentage: "15"
  storageReservedPercentageForDefaultDisk: "15"

persistence:
  reclaimPolicy: Retain

defaultBackupStore:
  backupTarget: s3://homelab-nieradko-com-backup@eu-central-003/
  backupTargetCredentialSecret: longhorn-b2-backup-secret
  pollInterval: 360

metrics:
  serviceMonitor:
    enabled: true
