apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: media-database-scheduledbackup
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: media-database-cluster
