apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: media-database-b2-backup-secret
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "250f68a3-6804-400c-a151-b390011a42f7"
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: "1b35313a-b218-408b-b6c6-b390011a1bc7"
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "d3b86766-5356-48df-bb23-b390011a5003"
