apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr-database
  namespace: media
spec:
  name: radarr
  owner: media-admin
  cluster:
    name: media-database-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr-log-database
  namespace: media
spec:
  name: radarr-log
  owner: media-admin
  cluster:
    name: media-database-cluster
