kind: Service
apiVersion: v1
metadata:
  name: downloads-service
  namespace: media
spec:
  selector:
    app: downloads
  type: ClusterIP
  ports:
    - name: web-ui
      protocol: TCP
      port: 9091
      targetPort: web-ui
