apiVersion: apps/v1
kind: Deployment
metadata:
  name: downloads-deployment
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downloads
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: downloads
    spec:
      containers:
        - name: downloads
          image: linuxserver/transmission:4.0.6
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media
              mountPath: /media
            - name: run
              mountPath: /run
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Warsaw
            - name: PEERPORT
              valueFrom:
                fileKeyRef:
                  key: PORTS
                  path: forwarded_port.env
                  volumeName: vpn-stats
                  optional: false
          ports:
            - name: web-ui
              containerPort: 9091
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
        - name: vpn
          image: qmcgaw/gluetun:v3.40.3
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "custom"
            - name: VPN_TYPE
              value: "wireguard"
            - name: DNS_ADDRESS
              value: "1.1.1.1"
            - name: DOT
              value: "off"
            - name: FIREWALL_INPUT_PORTS
              value: "9091"
            - name: VPN_PORT_FORWARDING
              value: "on"
            - name: VPN_PORT_FORWARDING_PROVIDER
              value: "private internet access"
            - name: VPN_PORT_FORWARDING_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pia-vpn-secret
                  key: username
            - name: VPN_PORT_FORWARDING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pia-vpn-secret
                  key: password
            - name: SERVER_NAMES
              valueFrom:
                fileKeyRef:
                  key: SERVER_NAME
                  path: wg0.conf.servername
                  volumeName: wgconfig
                  optional: false
            - name: VPN_PORT_FORWARDING_UP_COMMAND
              value: '/bin/sh -c "echo PORTS={{PORTS}} > /tmp/gluetun/forwarded_port.env"'
          volumeMounts:
            - mountPath: /gluetun/wireguard/
              name: wgconfig
              readOnly: true
            - mountPath: /tmp/gluetun
              name: vpn-stats
          readinessProbe:
            exec:
              command:
                - /gluetun-entrypoint
                - healthcheck
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 1
          livenessProbe:
            exec:
              command:
                - /gluetun-entrypoint
                - healthcheck
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 1
          lifecycle:
            postStart:
              exec:
                command:
                  [
                    "/bin/sh",
                    "-c",
                    "(ip rule del table 51820; ip -6 rule del table 51820) || true",
                  ]
      initContainers:
        - name: generate-wg-config
          image: ghcr.io/kanareklife/pia-wg-config:v1.2.0
          args:
            [
              "-r",
              "$(PIA_REGION)",
              "-o",
              "/out/wg0.conf",
              "--servername-file",
              "/out/wg0.conf.servername",
              "$(PIA_USERNAME)",
              "$(PIA_PASSWORD)",
            ]
          env:
            - name: PIA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: pia-vpn-secret
                  key: username
            - name: PIA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pia-vpn-secret
                  key: password
            - name: PIA_REGION
              value: "fi"
          volumeMounts:
            - mountPath: /out
              name: wgconfig
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: downloads-config-pvc
        - name: media
          persistentVolumeClaim:
            claimName: media-pvc
        - name: wgconfig
          emptyDir: {}
        - name: vpn-stats
          emptyDir: {}
        - name: run
          emptyDir: {}
