apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: suwayomi-server-auth-secret
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: "c2cf2718-7408-481d-9000-b3ea013bb9ee"
    - secretKey: password
      remoteRef:
        key: "69894a9c-55b2-49b6-9c9e-b3ea013abefc"
