apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sonarr-database
  namespace: media
spec:
  name: sonarr
  owner: media-admin
  cluster:
    name: media-database-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: sonarr-log-database
  namespace: media
spec:
  name: sonarr-log
  owner: media-admin
  cluster:
    name: media-database-cluster
