apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Infrastructure Project
  sourceRepos:
    - https://github.com/KanarekLife/homelab-v2
    - https://argoproj.github.io/argo-helm
    - https://kubernetes-sigs.github.io/metrics-server/
    - https://helm.cilium.io/
    - https://github.com/alex1989hu/kubelet-serving-cert-approver
    - https://charts.jetstack.io
    - https://github.com/kubernetes-sigs/gateway-api.git
    - https://charts.external-secrets.io
    - https://charts.goauthentik.io
    - https://cloudnative-pg.io/charts
    - https://intel.github.io/helm-charts
    - https://kubernetes-sigs.github.io/node-feature-discovery/charts
    - https://github.com/intel/intel-device-plugins-for-kubernetes
    - https://charts.longhorn.io/
    - https://prometheus-community.github.io/helm-charts
  destinations:
    - namespace: "*"
      name: in-cluster
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
