kind: ConfigMap
apiVersion: v1
metadata:
  name: files-configmap
  namespace: media
data:
  config.yaml: |
    server:
      sources:
        - path: /media
          name: Media
      cacheDir: /cache
    auth:
      methods:
        password:
          enabled: false
        oidc:
          enabled: true
          issuerUrl: https://login.nieradko.com/application/o/files/
          scopes: "email openid profile groups"
          userIdentifier: "preferred_username"
          createUser: true
          adminGroup: "Files Admins"
          groupsClaim: "groups"
