apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: suwayomi-backup-database
  namespace: media
spec:
  name: suwayomi-backup
  owner: media-admin
  cluster:
    name: media-database-cluster
