kind: Service
apiVersion: v1
metadata:
  name: suwayomi-backup-server-service
  namespace: media
spec:
  selector:
    app: suwayomi-backup-server
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 4567
      targetPort: 4567
