apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: suwayomi-backup-server-auth-secret
  namespace: media
  annotations:
    argocd.argoproj.io/sync-options: Prune=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  data:
    - secretKey: username
      remoteRef:
        key: "19783af0-a4ee-4422-9661-b3f6010d7683"
    - secretKey: password
      remoteRef:
        key: "d6cade65-4ef0-4695-985f-b3f6010d85f1"
