apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-pg-scheduledbackup
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: authentik-pg-cluster
