kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: cloudnative-pg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://cloudnative-pg.io/charts
      chart: cloudnative-pg
      targetRevision: 0.27.1
      helm:
        valueFiles:
          - $repo/kubernetes/infrastructure/cloudnative-pg/meta/values.yaml
    - repoURL: https://cloudnative-pg.io/charts
      chart: plugin-barman-cloud
      targetRevision: 0.4.0
    - repoURL: https://github.com/KanarekLife/homelab-v2
      targetRevision: main
      ref: repo
  destination:
    name: in-cluster
    namespace: cloudnative-pg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
