apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-ssd-storage
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  diskSelector: "SSD"
