kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
    - repoURL: https://charts.goauthentik.io
      chart: authentik
      targetRevision: 2025.12.3
      helm:
        releaseName: authentik
        valueFiles:
          - $repo/kubernetes/infrastructure/authentik/meta/values.yaml
    - repoURL: https://github.com/KanarekLife/homelab-v2
      targetRevision: HEAD
      ref: repo
    - repoURL: https://github.com/KanarekLife/homelab-v2
      targetRevision: HEAD
      path: kubernetes/infrastructure/authentik/manifests
  destination:
    name: in-cluster
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
