replicaCount: 1

strategy:
  type: RollingUpdate

rootPath: /

envs:
  - name: UI_APPNAME
    value: "Stirling PDF"
  - name: UI_HOMEDESCRIPTION
    value: "Your locally hosted one-stop-shop for all your PDF needs."
  - name: UI_APPNAMENAVBAR
    value: "Stirling PDF"
  - name: LANGS
    value: "en_GB"
  - name: SYSTEM_DEFAULTLOCALE
    value: "en-GB"
  - name: SECURITY_ENABLELOGIN
    value: "false"
  - name: DISABLE_ADDITIONAL_FEATURES
    value: "false"
  - name: FAT_DOCKER
    value: "true"
  - name: SYSTEM_MAXFILESIZE
    value: "500"
  - name: SYSTEM_GOOGLEVISIBILITY
    value: "false"

probes:
  liveness:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  livenessHttpGetConfig:
    scheme: HTTP
  readiness:
    enabled: false
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 1
    successThreshold: 1
    failureThreshold: 3
  readinessHttpGetConfig:
    scheme: HTTP
